### ISSUE TITLE
Random crash of Unity editor when exiting play

### ISSUE THREAD

**Issue by bdovaz** [Cysharp/YetAnotherHttpHandler#10]
In the log editor I see this error in the last lines:

```
InvalidOperationException: Writing is not allowed after writer was completed.
  at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed () [0x00005] in <f522e5f35b614d15ab6cdc06f9a4e691>:0 
  at System.IO.Pipelines.Pipe.GetSpan (System.Int32 sizeHint) [0x0000d] in <f522e5f35b614d15ab6cdc06f9a4e691>:0 
  at System.IO.Pipelines.Pipe+DefaultPipeWriter.GetSpan (System.Int32 sizeHint) [0x00000] in <f522e5f35b614d15ab6cdc06f9a4e691>:0 
  at Cysharp.Net.Http.NativeLibraryWrapper+Response.Write (System.ReadOnlySpan`1[T] data) [0x00001] in {MY_PROJECT}\Packages\YetAnotherHttpHandler\NativeLibraryWrapper.cs:403 
  at Cysharp.Net.Http.NativeLibraryWrapper.OnReceive (System.Int32 reqSeq, System.UIntPtr length, System.Byte* buf) [0x0003e] in {MY_PROJECT}\Packages\YetAnotherHttpHandler\NativeLibraryWrapper.cs:550 
  at (wrapper native-to-managed) Cysharp.Net.Http.NativeLibraryWrapper.OnReceive(int,uintptr,byte*)
```

I have also seen this error randomly when running with N clients at the same time.

**Comment by vrenken** [comment]
I can confirm that something fishy is going on in the shutdown/startup of this handler (great initiative btw).

For me it happens randomly at exit or enter of play mode and completely crashes Unity. It does not happen always, but I would say it definitely requires fewer than 5 application starts to cause the crash, making it a pain to develop/debug an application. If in the project the handler is replaced with the default one then Unity becomes stable again.

If time permits I’ll try to setup a minimal project to reproduce the issue in the next few days, shouldn’t be that hard.

Keep up the great work & greetings from Germany!

Peter Vrenken

**Comment by yusufkildan** [comment]
I'm having the same problem. If I reopen Unity after about 30 seconds after sending it to the background, this crash occurs.


Here is the more detailed log and stack trace:

```


=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x2c07534dc - /Applications/Unity/Hub/Editor/2021.3.30f1/Unity.app/Contents/Frameworks/MonoBleedingEdge/MonoEmbedRuntime/osx/libmonobdwgc-2.0.dylib : mono_dump_native_crash_info
	0x2c07159d8 - /Applications/Unity/Hub/Editor/2021.3.30f1/Unity.app/Contents/Frameworks/MonoBleedingEdge/MonoEmbedRuntime/osx/libmonobdwgc-2.0.dylib : mono_handle_native_crash
	0x2c069e0d8 - /Applications/Unity/Hub/Editor/2021.3.30f1/Unity.app/Contents/Frameworks/MonoBleedingEdge/MonoEmbedRuntime/osx/libmonobdwgc-2.0.dylib : mono_sigsegv_signal_handler_debug
	0x18add6a24 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x393f9e8a4 - Unknown
	0x393f9e8a4 - Unknown
	0x393f9e2a4 - Unknown
	0x39226c054 - Unknown
	0x39270afcc - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN11yaha_native7binding18yaha_request_begin28_$u7b$$u7b$closure$u7d$$u7d$17hf56d40886751ab86E
	0x392708adc - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio4loom3std11unsafe_cell19UnsafeCell$LT$T$GT$8with_mut17hf6b59fa4d6c36c8aE
	0x3926cf878 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime4task4core17Core$LT$T$C$S$GT$4poll17h45ca054366c8b38eE
	0x3926b1114 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime4task7harness20Harness$LT$T$C$S$GT$4poll17hbe0a25a56342561aE
	0x39280f1f0 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime9scheduler12multi_thread6worker7Context8run_task17h6af793b981f48c8aE
	0x39280e85c - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime9scheduler12multi_thread6worker7Context3run17hf93829ea7712a9cfE
	0x39280a918 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime7context6scoped15Scoped$LT$T$GT$3set17he96f85794a76ec04E
	0x392813604 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime7context7runtime13enter_runtime17hdf0c84ce8dba9c89E
	0x39280e1d0 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime9scheduler12multi_thread6worker3run17h934de7126e267f27E
	0x392806a18 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio4loom3std11unsafe_cell19UnsafeCell$LT$T$GT$8with_mut17h8db29b7f0c3fa7d0E
	0x39280929c - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime4task4core17Core$LT$T$C$S$GT$4poll17h54b41038c8b290c4E
	0x392800824 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime4task7harness20Harness$LT$T$C$S$GT$4poll17h23c7fe948ce3fedcE
	0x39281c6c4 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN5tokio7runtime8blocking4pool5Inner3run17h610879e8834b2350E
	0x392814618 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hc501116405218d2fE
	0x392802ba4 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h777e788b7fa9e9a6E
	0x39284c154 - /Users/voys/Desktop/Projects/parrot-Unity/Library/PackageCache/com.cysharp.yetanotherhttphandler@bd2c526021/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/runtimes/osx-arm64/native/libCysharp.Net.Http.YetAnotherHttpHandler.Native.dylib : _ZN3std3sys4unix6thread6Thread3new12thread_start17h7f56b35fafcfec87E
	0x18ada7fa8 - /usr/lib/system/libsystem_pthread.dylib : _pthread_start
	0x18ada2da0 - /usr/lib/system/libsystem_pthread.dylib : thread_start

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x15397171200x from 0x15349952512x
Pkilling 0x12459470848x from 0x15349952512x
Pkilling 0x12463763456x from 0x15349952512x
Pkilling 0x12468056064x from 0x15349952512x
Pkilling 0x12472348672x from 0x15349952512x
Pkilling 0x12476641280x from 0x15349952512x
Pkilling 0x12571193344x from 0x15349952512x
Pkilling 0x12480933888x from 0x15349952512x
Pkilling 0x15339122688x from 0x15349952512x
Pkilling 0x11816087552x from 0x15349952512x
Pkilling 0x12391346176x from 0x15349952512x
Pkilling 0x12352909312x from 0x15349952512x
Pkilling 0x8151801984x from 0x15349952512x
Pkilling 0x15364976640x from 0x15349952512x
Pkilling 0x12461617152x from 0x15349952512x
Pkilling 0x12465909760x from 0x15349952512x
Pkilling 0x12470202368x from 0x15349952512x
Pkilling 0x11827130368x from 0x15349952512x
Pkilling 0x12474494976x from 0x15349952512x
Pkilling 0x12478787584x from 0x15349952512x
Pkilling 0x12573339648x from 0x15349952512x
Obtained 25 stack frames.
Pkilling 0x12483080192x from 0x15349952512x
Pkilling 0x15423008768x from 0x15349952512x
Pkilling 0x12573913088x from 0x15349952512x
Pkilling 0x12577697792x from 0x15349952512x
Pkilling 0x12389199872x from 0x15349952512x
Pkilling 0x12350763008x from 0x15349952512x
Pkilling 0x12355055616x from 0x15349952512x
#0  0x000002c089d034 in mono_get_hazardous_pointer
#1  0x000002c07f43f0 in mono_jit_info_table_find_internal
#2  0x000002c07127bc in mini_jit_info_table_find_ext
#3  0x000002c0711938 in mono_summarize_unmanaged_stack
#4  0x000002c0848644 in mono_threads_summarize_native_self
#5  0x000002c08489a0 in mono_threads_summarize_execute_internal
#6  0x000002c0848768 in mono_threads_summarize_execute
#7  0x000002c07528d8 in sigterm_signal_handler
#8  0x0000018add6a24 in _sigtramp
#9  0x225180018ada8574 in _pthread_cond_wait
#10 0x7b58800392826ec4 in parking_lot::condvar::Condvar::wait_until_internal::ha089b7ca447d7f6a
#11 0x0000039280497c in tokio::runtime::scheduler::multi_thread::park::Parker::park::hd0649785ed3020c1
#12 0x0000039280f5a8 in tokio::runtime::scheduler::multi_thread::worker::Context::park_timeout::hd8e2acf58d3de59b
#13 0x0000039280ebcc in tokio::runtime::scheduler::multi_thread::worker::Context::run::hf93829ea7712a9cf
#14 0x0000039280a918 in tokio::runtime::context::scoped::Scoped$LT$T$GT$::set::he96f85794a76ec04
#15 0x00000392813604 in tokio::runtime::context::runtime::enter_runtime::hdf0c84ce8dba9c89
#16 0x0000039280e1d0 in tokio::runtime::scheduler::multi_thread::worker::run::h934de7126e267f27
#17 0x00000392806a18 in tokio::loom::std::unsafe_cell::UnsafeCell$LT$T$GT$::with_mut::h8db29b7f0c3fa7d0
#18 0x0000039280929c in tokio::runtime::task::core::Core$LT$T$C$S$GT$::poll::h54b41038c8b290c4
#19 0x00000392800824 in tokio::runtime::task::harness::Harness$LT$T$C$S$GT$::poll::h23c7fe948ce3fedc
#20 0x0000039281c6c4 in tokio::runtime::blocking::pool::Inner::run::h610879e8834b2350
Entering thread summarizer pause from 0x15349952512x
#21 0x00000392814618 in std::sys_common::backtrace::__rust_begin_short_backtrace::hc501116405218d2f
#22 0x00000392802ba4 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h777e788b7fa9e9a6
#23 0x0000039284c154 in std::sys::unix::thread::Thread::new::thread_start::h7f56b35fafcfec87
#24 0x0000018ada7fa8 in _pthread_start
Obtained 25 stack frames.
#0  0x000002c089d034 in mono_get_hazardous_pointer
#1  0x000002c07f43f0 in mono_jit_info_table_find_internal
#2  0x000002c07127bc in mini_jit_info_table_find_ext
#3  0x000002c0711938 in mono_summarize_unmanaged_stack
#4  0x000002c0848644 in mono_threads_summarize_native_self
#5  0x000002c08489a0 in mono_threads_summarize_execute_internal
#6  0x000002c0848768 in mono_threads_summarize_execute
#7  0x000002c07528d8 in sigterm_signal_handler
#8  0x0000018add6a24 in _sigtramp
#9  0xe54300018ada8574 in _pthread_cond_wait
#10 0x9862800392826ec4 in parking_lot::condvar::Condvar::wait_until_internal::ha089b7ca447d7f6a
#11 0x0000039280497c in tokio::runtime::scheduler::multi_thread::park::Parker::park::hd0649785ed3020c1
#12 0x0000039280f5a8 in tokio::runtime::scheduler::multi_thread::worker::Context::park_timeout::hd8e2acf58d3de59b
#13 0x0000039280ebcc in tokio::runtime::scheduler::multi_thread::worker::Context::run::hf93829ea7712a9cf
#14 0x0000039280a918 in tokio::runtime::context::scoped::Scoped$LT$T$GT$::set::he96f85794a76ec04
#15 0x00000392813604 in tokio::runtime::context::runtime::enter_runtime::hdf0c84ce8dba9c89
#16 0x0000039280e1d0 in tokio::runtime::scheduler::multi_thread::worker::run::h934de7126e267f27
#17 0x00000392806a18 in tokio::loom::std::unsafe_cell::UnsafeCell$LT$T$GT$::with_mut::h8db29b7f0c3fa7d0
#18 0x0000039280929c in tokio::runtime::task::core::Core$LT$T$C$S$GT$::poll::h54b41038c8b290c4
#19 0x00000392800824 in tokio::runtime::task::harness::Harness$LT$T$C$S$GT$::poll::h23c7fe948ce3fedc
#20 0x0000039281c6c4 in tokio::runtime::blocking::pool::Inner::run::h610879e8834b2350
#21 0x00000392814618 in std::sys_common::backtrace::__rust_begin_short_backtrace::hc501116405218d2f
#22 0x00000392802ba4 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h777e788b7fa9e9a6
#23 0x0000039284c154 in std::sys::unix::thread::Thread::new::thread_start::h7f56b35fafcfec87
#24 0x0000018ada7fa8 in _pthread_start

```

**Comment by doyasu24** [comment]
I have confirmed Unity Editor no longer crashes in v1.0.0.
Unity 2022.3.16f1 M3 Mac

Thank you!
