### ISSUE TITLE
Unity crash if server has an non-ascii character

### ISSUE THREAD

**Issue by RubenGarcia** [Cysharp/YetAnotherHttpHandler#16]
When address contains non-ascii codes:

This code
```
            using var channel = GrpcChannel.ForAddress(address, new GrpcChannelOptions()
                {
                    HttpHandler = new YetAnotherHttpHandler(),
                    DisposeHttpClient = true
                }
            );
```
produces
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: http::Error(InvalidUri(InvalidUriChar))', yaha_native\src\binding.rs:291:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', yaha_native\src\binding.rs:415:67
Crash!!!
```
Found when address by mistake had a bogus character at the end with code 8xxx.
Please catch the error and report, avoiding crashing Unity.

**Comment by RubenGarcia** [comment]
This happens e.g. if you mistakenly get your text from the TextMeshProUGUI object inside the TMP_InputField, instead of the correct TMP_InputField.
Since the presence of extra characters is undocumented, this can be difficult to debug, especially if Unity itself crashes. Please fix.
